// Unity Build generated by CMake
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/core_functions/scalar/random/random.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/core_functions/scalar/random/setseed.cpp>
