// Unity Build generated by CMake
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/catalog/default/default_functions.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/catalog/default/default_generator.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/catalog/default/default_schemas.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/catalog/default/default_table_functions.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/catalog/default/default_types.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/catalog/default/default_views.cpp>
