// Unity Build generated by CMake
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/core_functions/scalar/union/union_extract.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/core_functions/scalar/union/union_tag.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/core_functions/scalar/union/union_value.cpp>
