// Unity Build generated by CMake
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/optimizer/rule/arithmetic_simplification.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/optimizer/rule/case_simplification.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/optimizer/rule/comparison_simplification.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/optimizer/rule/conjunction_simplification.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/optimizer/rule/constant_folding.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/optimizer/rule/date_part_simplification.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/optimizer/rule/distributivity.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/optimizer/rule/empty_needle_removal.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/optimizer/rule/enum_comparison.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/optimizer/rule/equal_or_null_simplification.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/optimizer/rule/in_clause_simplification_rule.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/optimizer/rule/join_dependent_filter.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/optimizer/rule/like_optimizations.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/optimizer/rule/move_constants.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/optimizer/rule/ordered_aggregate_optimizer.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/optimizer/rule/regex_optimizations.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/optimizer/rule/timestamp_comparison.cpp>
