// Unity Build generated by CMake
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/common/adbc/nanoarrow/metadata.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/common/adbc/nanoarrow/schema.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/common/adbc/nanoarrow/allocator.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/common/adbc/nanoarrow/single_batch_array_stream.cpp>
