// Unity Build generated by CMake
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/parser/transform/tableref/transform_base_tableref.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/parser/transform/tableref/transform_join.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/parser/transform/tableref/transform_from.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/parser/transform/tableref/transform_pivot.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/parser/transform/tableref/transform_subquery.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/parser/transform/tableref/transform_table_function.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/parser/transform/tableref/transform_tableref.cpp>
