// Unity Build generated by CMake
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/common/arrow/arrow_appender.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/common/arrow/arrow_converter.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/common/arrow/arrow_util.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/common/arrow/arrow_merge_event.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/common/arrow/arrow_query_result.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/common/arrow/arrow_wrapper.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/common/arrow/physical_arrow_collector.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/common/arrow/physical_arrow_batch_collector.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/common/arrow/schema_metadata.cpp>
