// Unity Build generated by CMake
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/function/scalar/operators/add.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/function/scalar/operators/arithmetic.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/function/scalar/operators/multiply.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/function/scalar/operators/subtract.cpp>
