// Unity Build generated by CMake
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/core_functions/aggregate/algebraic/avg.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/core_functions/aggregate/algebraic/covar.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/core_functions/aggregate/algebraic/stddev.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/core_functions/aggregate/algebraic/corr.cpp>
