// Unity Build generated by CMake
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/common/serializer/binary_serializer.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/common/serializer/binary_deserializer.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/common/serializer/buffered_file_reader.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/common/serializer/buffered_file_writer.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/common/serializer/memory_stream.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/common/serializer/serializer.cpp>
