// Unity Build generated by CMake
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/function/pragma/pragma_functions.cpp>
#include </Users/qiu/Documents/codes/cpp/duckdb-learn/src/function/pragma/pragma_queries.cpp>
